### ISSUE TITLE
After the metaserver stops for a period of time, it starts and automatically exits

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1155]
**Describe the bug (描述bug)**
After the metaserver stops for a period of time, it starts and automatically exits

**To Reproduce (复现方法)**
1、stop metaserver
2、start metaserver
![image](https://user-images.githubusercontent.com/67582932/157403582-77335fbd-23ef-42cf-a2e5-e22c240f94f7.png)
![image](https://user-images.githubusercontent.com/67582932/157403617-47472df7-6b23-4856-83e6-5da5ad2ce47c.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wu-hanqing** [comment]
curvefs-metaserver exited because s3 compact task access a dangling pointer.
![Uploading image.png…]()

and the reason is copyset is been purged because current metaserver has been down for a long time, and MDS's scheduler has already transferred copysets in current metaserver to other metaservers.

so after current metaserver starts again, all copysets should be deleted.

s3 compact task started after the corresponding copyset started and owns a raw pointer of the copyset, but when purging copyset, we don't cancel corresponding s3 compact tasks.
so when s3 compact task is ready to execute, the process exited.
