### ISSUE TITLE
CI： Inconsistent data in md5sum file

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1242]
**Describe the bug (描述bug)**
http://59.111.91.248:8080/job/curve_fs_failover_test/474/robot/report/log.html

logs in : pubbeta2-curve3 : /data/logs/curvefs/
![image](https://user-images.githubusercontent.com/67582932/161362873-a43a3d64-d805-49f7-b7e9-51a9a7b27cb5.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by ilixiaocui** [comment]
Prepare:
when the data is inconsistent, use hexdump to read and save the two files respectively.

Scene reproduction:
![image](https://user-images.githubusercontent.com/15689619/163299214-7dd4e09d-4b53-4629-a201-f86adaa8d19d.png)

Analyze:
`diff -a test1.hex1 test1.hex2


 
4811743c4811743
< 1315c000 2000 0200 0000 0000 9c06 a96a cdf2 0ae9
---
> 1315c000 b000 2961 0000 0000 9c06 a96a cdf2 0ae9
4811746,4811747c4811746,4811747
< 1315c030 0009 0000 0000 0000 622e 0cd4 0000 0000
< 1315c040 3000 1141 0000 0000 94a9 c623 d05c 0c90
---
> 1315c030 0009 0000 0000 0000 baef 132a 0000 0000
> 1315c040 0000 2a1c 0000 0000 94a9 c623 d05c 0c90
4811755c4811755
< 1315c0c0 b000 2961 0000 0000 8589 dfe9 15d6 096a
---
> 1315c0c0 1000 342c 0000 0000 8589 dfe9 15d6 096a`

**Comment by h0hmj** [comment]
1. test is running round and round again, and will not clean the data from last round
2. after new write, there will be 2 version data of some s3obj with the same objname
3. old one -> s3, new one -> diskcache(have not upload to the s3, but metadata has been updated)
4. so s3compact will read the old one.


root cause:
1. environment is dirty, we need clean it before next round.
2. diskcache will update metadata before upload data. it's hard to determine which is the right data when environment is dirty and there are multi clients.
