### ISSUE TITLE
Copyset is not automatically migrated after stopping metaserver

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1382]
**Describe the bug (描述bug)**

Copyset is not automatically migrated after stopping metaserver
**To Reproduce (复现方法)**
1、stop metaserver
2、wait 4 hours
3、
![image](https://user-images.githubusercontent.com/67582932/165904329-707acd96-3d97-42c5-81c0-894178ab8ef5.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cw123** [comment]
I 2022-04-29T12:02:54.543547+0800    80 recoverScheduler.cpp:34] recoverScheduler begin.
I 2022-04-29T12:02:54.543730+0800    80 operatorControllerTemplate.h:141] add operator [startEpoch: 3, copysetID: (1,5), priority: 2, step: change peer from 5 to 6] fail because of oncurrency exceed
W 2022-04-29T12:02:54.543761+0800    80 recoverScheduler.cpp:95] recover scheduler add operator [startEpoch: 3, copysetID: (1,5), priority: 2, step: change peer from 5 to 6] on [copysetId:(1,5), epoch:3, leader:2, peers:(1,2,5,), canidate:0, has configChangeInfo:0] fail
I 2022-04-29T12:02:54.543777+0800    80 operatorControllerTemplate.h:141] add operator [startEpoch: 3, copysetID: (1,6), priority: 2, step: change peer from 5 to 6] fail because of oncurrency exceed
W 2022-04-29T12:02:54.543783+0800    80 recoverScheduler.cpp:95] recover scheduler add operator [startEpoch: 3, copysetID: (1,6), priority: 2, step: change peer from 5 to 6] on [copysetId:(1,6), epoch:3, leader:4, peers:(2,4,5,), canidate:0, has configChangeInfo:0] fail

**Comment by cw123** [comment]
the recover generate operator, but the operator exceed the  concurrency
the concurrent is set 1 at mds.conf.  
mds.schduler.operator.concurrent=1

**Comment by cw123** [comment]
过了6天，copyset配置变更还是卡在这里
![image](https://user-images.githubusercontent.com/4277834/166895753-35cf3739-0486-4676-901d-891117c9c02e.png)

**Comment by cw123** [comment]
mds日志里面，心跳有报这个错误
W 2022-05-05T17:43:33.544570+0800   106 heartbeat_manager.cpp:233] leader not found, poolid: 1, copysetid: 1
W 2022-05-05T17:43:37.469429+0800   100 heartbeat_manager.cpp:233] leader not found, poolid: 1, copysetid: 4
W 2022-05-05T17:43:42.525686+0800    90 heartbeat_manager.cpp:233] leader not found, poolid: 1, copysetid: 2
W 2022-05-05T17:43:43.544281+0800    98 heartbeat_manager.cpp:233] leader not found, poolid: 1, copysetid: 1
W 2022-05-05T17:43:47.469271+0800    94 heartbeat_manager.cpp:233] leader not found, poolid: 1, copysetid: 4
W 2022-05-05T17:43:52.526186+0800    25 heartbeat_manager.cpp:233] leader not found, poolid: 1, copysetid: 2
W 2022-05-05T17:43:53.545147+0800   107 heartbeat_manager.cpp:233] leader not found, poolid: 1, copysetid: 1

**Comment by cw123** [comment]
metaserver有很多这个日志
![image](https://user-images.githubusercontent.com/4277834/166913081-d26f6311-62a5-4acb-bc20-c7990cef54ca.png)

**Comment by wu-hanqing** [comment]
this problem is introduced by #1211, and the reason is when dispatching configuration change to metaserver, MDS will ensure that the target copyset is not creating state.

but #1211 doesn't reset creating state, so the configuration change doesn't dispatch.

**Comment by cw123** [comment]
> this problem is introduced by #1211, and the reason is when dispatching configuration change to metaserver, MDS will ensure that the target copyset is not creating state.
> 
> but #1211 doesn't reset creating state, so the configuration change doesn't dispatch.

will fix it in https://github.com/opencurve/curve/pull/1417

**Comment by cw123** [comment]
fix it, merge to master https://github.com/opencurve/curve/pull/1417
