### ISSUE TITLE
curvefs/metaserver: Can metaserver's raft snapshot implementation be asynchronous

### ISSUE THREAD

**Issue by ilixiaocui** [opencurve/curve#1617]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
Now the raft snapshot on the metaserver side blocks normal io，we need to evaluate whether snapshots can be implemented in an asynchronous manner.

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by wuhongsong** [comment]
@ilixiaocui

**Comment by ilixiaocui** [comment]
> @ilixiaocui

still have this problem, tag the issue as `good first issue`.

**Comment by Ziy1-Tan** [comment]
take

**Comment by Ziy1-Tan** [comment]
I have read https://github.com/baidu/braft/blob/master/docs/cn/server.md, I think `on_snapshot_load` and `on_snapshot_save` block io, point out my misunderstanding if any plz.

**Comment by wu-hanqing** [comment]
`on_snapshot_load` doesn't matters because when a replica is loading from snapshot, it should not be a leader of this group and doesn't serve the end user's request.

Currently, we implement `on_snapshot_save` synchronous because we need to flush rocksdb's memtable to disk, so in the progress other requests are blocked.

But this can be implemented using other methods, for example, we can combine each operation with raft apply index, and when a memtable is flushed to disk then we can callback raft to truncate WAL with the lastest apply index in current memtable.

**Comment by Ziy1-Tan** [comment]
Let me take a look, thx!

**Comment by zhanghuidinah** [comment]
- **This issue has been chosen for community developer activities.  Welcome to feel free to try it. After the PR is merged, you will receive a gift package and a certificate as a community contributor.**

- **Developer Activities Registration Steps please ref https://github.com/opencurve/curve/issues/2334#issuecomment-1504723771**

**Comment by wu-hanqing** [comment]
> can i take this issue?

hi @pengpengSir, since @Ziy1-Tan has already startted, you can find other interesting issues in #2334

**Comment by NaturalSelect** [comment]
Can I apply for it?

**Comment by wuhongsong** [comment]
> Can I apply for it?

of course，You are welcome to participate, please add ”OpenCurve_bot“ on WeChat.

**Comment by 1797818494** [comment]
Can I apply for it?
