### ISSUE TITLE
The length of the file written by the mount point is not updated

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#1845]
**Describe the bug (描述bug)**

The length of the file written by the mount point is not updated

**To Reproduce (复现方法)**
1、mount fs1 -> test1 fs1 -> test2
2、echo a > test1/a
3、cat test2/a -> a
4、echo b >> test1/a
sleep 5mins
5、cat test2/a -> a
6、umount test5 test6 /  mount test5 test6

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wu-hanqing** [comment]
here is a workflow that can reproduce this problem, 

```
                          │
                          │
           mount_1        │     mount_2
──────────────────────────┼───────────────────────────
                          │
    1. echo "a" > file    │
                          │
    2. cat file           │
       > a                │
                          │   3. echo "a" >> file
                          │
                          │   4. cat file
                          │      > a
                          │        a
                          │
                          │
    5. cat file           │
       > a                │
                          │
                          │
    6. umount & mount     │
                          │
                          │
    7. cat file           │
       > a                │
```

In theory, step 7 should output double `a` like step 4, but it doesn't, because `file`'s length is still `2` instead of `4`.

The reason is:
1. we mount a filesystem twice but disable close-to-open guarantee and manipulate the same file in different mount points
2. step 5 makes the inode dirty in the cache, which means it will update metadata to metaserver, and this leads to the inode's length changing from `4` to `2`. 

If we skip step 5 and remount mount_1 after step 4, **in most cases**, we will get a correct result.

<hr/>

So, two things should be clarified
1. Is it necessary to make the inode dirty in step 5?
2. Should we guarantee the result in this case?
