### ISSUE TITLE
pjdtest has many failures

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#2243]
**Describe the bug (描述bug)**

pjdtest has many failures

**To Reproduce (复现方法)**

![image](https://user-images.githubusercontent.com/67582932/218044119-20715ed6-b41a-4eb6-b163-586162484729.png)
#!/usr/bin/env bash

set -e

wget http://59.111.88.148:8082/pjdtest.tar.gz
tar zxvf pjdtest.tar.gz
cd pjdfstest-master
autoreconf -ifs
./configure
make pjdfstest
cd ..
mkdir tmp
cd tmp
sudo prove -r -v --exec 'bash -x' ../pjdfs*/tests
cd ..
rm -rf tmp pjd*
**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Cyber-SiKu** [comment]
![image](https://user-images.githubusercontent.com/15775037/218054348-9ab129ec-60ed-457a-9abb-7b0bba48d4fc.png)

**Comment by wuhongsong** [comment]
Conclusion: 
   There is no problem in not opening cto; 
   cto is opened is what makes this problem possible;

- Open cto

Creating the directory itself is fine; But when you create a directory and then create subdirectories, you have problems. The process of creating a subdirectory is to create a subdirectory dentry and then update the parent directory nlinks count. To update the parent directory  nlink count function, we need to obtain the parent directory's inode. When cto is enabled, we will go to metaserver to get the inode, and then add 1 to the nlinks count. So the curve-fuse end increases here, and you have a problem.

But a few seconds later, when the inode properties are retrieved again, the nlink counts is correct. Since the default gap is at most 5 seconds (the interval between metadata sync), so you can get the correct nlink value later.

after Inode metadata has synced, inode is not dirty, then InodeCacheManagerImpl: : NeedUseCache return value is false, So the GetInode function is going to fetch the inode from the metaserver

- No cto

The inodes of the parent directory are obtained directly from the client cache, not from metasetver, so there is no problem

**Comment by wuhongsong** [comment]
Possible solutions：

If you can determine whether the parent inode is obtained from the metaserver or client cahce. when the parent directory nlink and time are updated on the client , maybe you can do follow：

-  if the parent inode is obtained from the cache; otherwise, do not update the increme
-  if the parent inode is obtained from the cache; when the parent directory nlink and time are updated on the client, 
update the increment nlink and time
