### ISSUE TITLE
Core dump occurs during data reading and writing at the FUSE mount point. 

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#2250]
**Describe the bug (描述bug)**

Core dump occurs during data reading and writing at the FUSE mount point. 
**To Reproduce (复现方法)**

![image](https://user-images.githubusercontent.com/67582932/219573465-aad480c7-4245-4aa7-9913-ecd2ce6623af.png)

**Expected behavior (期望行为)**
![image](https://user-images.githubusercontent.com/67582932/219573470-749a3a76-6959-4915-8344-2a732526b411.png)

**Versions (各种版本)**
OS:
Compiler:
branch:
commit id:

**Additional context/screenshots (更多上下文/截图)**

**Comment by Cyber-SiKu** [comment]
@ilixiaocui Is this still going on?

**Comment by ilixiaocui** [comment]
![image](https://user-images.githubusercontent.com/15689619/222074739-f182ddec-d700-410a-bb00-2a99d1fec582.png)
![image](https://user-images.githubusercontent.com/15689619/222074760-212cd165-2c58-4138-9ba0-64c5ee62c074.png)

The data length read from memcache is wrong. The reason is the same as #2251.
