### ISSUE TITLE
shutdown one etcd\mds\metaserver,  io hang

### ISSUE THREAD

**Issue by YunhuiChen** [opencurve/curve#732]
**Describe the bug (描述bug)**

shutdown one etcd\mds\metaserver,  io hang
**To Reproduce (复现方法)**
1、write vdbench
2、reboot one host, have (etcd \ mds \ metaserver)
3、io hange 4-5 minutes

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/67582932/143396222-8b717560-885a-45d8-8200-36bbf70f5d77.png)
![image](https://user-images.githubusercontent.com/67582932/143396375-df2143f6-c19c-4f12-83f5-769e7f8431a6.png)

**Comment by wu-hanqing** [comment]
this problem is mainly caused by configuration items, specifically, they are
```bash
# RPC total retry time with MDS
mdsOpt.mdsMaxRetryMS=16000

# RPC timeout for once communication with MDS
mdsOpt.rpcRetryOpt.rpcTimeoutMs=5000

# Switch if the number of consecutive retries on the current MDS exceeds the limit.
# The number of failures includes the number of timeout retries
mdsOpt.rpcRetryOpt.maxFailedTimesBeforeChangeAddr=3

# The normal retry times for trigger wait strategy
mdsOpt.rpcRetryOpt.normalRetryTimesBeforeTriggerWait=3

# Sleep interval for wait
mdsOpt.rpcRetryOpt.waitSleepMs=1000

# close socket after defer.close.second
rpc.defer.close.second=600
```
from curvefs/conf/client.conf.

The first five items are used to control RPC with MDS, when hosts are directly powered down, RPC will timeout after `mdsOpt.rpcRetryOpt.rpcTimeoutMs` because the bottom TCP connection cannot immediately notice the remote server is down until keepalive triggered. And after consecutive 3(`mdsOpt.rpcRetryOpt.maxFailedTimesBeforeChangeAddr`) RPC timeout, then we sleep one seconds(`mdsOpt.rpcRetryOpt.waitSleepMs`) and retry another MDS. But 16 seconds have elapsed, so we won't retry again(total retry time is 16 seconds `mdsOpt.mdsMaxRetryMS`). So, in the end, AllocS3ChunkId is failed, data cache flush is failed, and user's write operations are blocked when write data cache is full.

Next data cache flush also invokes AllocS3ChunkId, but it reuses the previous 'broken' TCP connection because only after 600 seconds(`rpc.defer.close.second`) TCP connections will get closed or remote server startup.
