### ISSUE TITLE
vebench test s3Compact cause data inconsistency

### ISSUE THREAD

**Issue by baijiaruo** [opencurve/curve#944]
**Describe the bug (描述bug)**
![image](https://user-images.githubusercontent.com/7495307/148347752-7cfe53eb-1f8e-47e6-87c5-71a74ff87831.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
curve-mds:
curve-chunkserver:
curve-snapshotcloneserver:
curve-sdk:
nebd:
curve-nbd:

**Additional context/screenshots (更多上下文/截图)**

**Comment by h0hmj** [comment]
1. client: do first write
2. metaserver: do compaction and change inode metadata, client's inodecache stale
3. client use stale cache , generate request and read s3, return obj not exist
4. client call inodecache clear and get latest inode  <----- problem here

problem: when clear inodecache, local client may be hold some newer not uploaded metaserver. calling clear will lost them.

we need make these changes persistent then get inode rather than calling clear directly.

related pr: #907

**Comment by baijiaruo** [comment]
vdbench config：
fsd=fsd1,anchor=/mnt/hy/test100/,depth=2,width=8,files=8,sizes=(100m,0),shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd1,threads=10,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=50
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=14400,interval=1

cmd：./vdbench -f config -jn
